name: dart_rest_api_starter_kit
description: Production-ready REST API starter kit with Dart/Shelf featuring JWT authentication, security middlewares, monitoring, and enterprise-grade architecture.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2
  sqlite3: ^2.9.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0

executables:
  mock_server: main
